// list of all the reviews
const review_list = [
    // {name: str, review: str, stars: int<1:5>, source:str<google,ha|homeadvisor}
    {name: "Walton M", review: "Couldn’t recommend them enough! James was kind and informative, and kept us in the loop the whole time. His worker Brian was unbelievable and worked incredibly hard - incredibly efficient. We were very impressed by his professionalism and thoroughness throughout every step of the work. We received quotes on other company’s and their price was also the best by a long shot", stars:5, source:"google"},
    {name: "Lisa L", review: "Called James McCasland, he was at my house within 20 minutes. My sump pump was not working. He had it fixed very quick, saved me from a long night. Highly recommend.", stars:5, source:"google"},
    {name: "Tony K", review: "James and his crew were great to work with - extremely knowledgeable and helped walk us through the whole process. We can already feel a difference in the humidity/temp in our home, would recommend to anyone!", stars:5, source:"google"},
    {name: "Mitch P", review: "My house was flooded in April as it was in 2009 also. This time around I called 4 different companies out to give me an estimate on the crawlspace damage. 1 company never showed, never got an estimate from #2, #3 was a high estimate. Middle Tn Crawlspace was already working in the neighborhood so I asked them to give me an estimate. I had it before they left. The estimate was much more reasonable than the other and James was very knowledgeable and communicated well what was needed. I am very happy with the completed encapsulation. I would recommend Middle Tn to others in need of this type of service. They did a excellent job! What a difference it makes!", stars:5, source:"google"},
    {name: "Periann A", review: "Affordable and professional. Team did a great job at waterproofing basement. Recommend.", stars:5, source:"google"},
    {name: "Gina Marie H", review: "We were having a moisture issue in our crawlspace. We made several calls and received quotes. And middle Tennessee crawlspace was by far the best choice we could have made. James and his team did an amazing job. Their price was more than reasonable and for the quality of their work they could have definitely asked for a lot more. James kept us informed about what he was doing and when he was doing it. He fixed the moisture issues and even the creaking in the floors. The time frame he gave was right on as well. If you need someone you can absolutely count on to do so the job right, give them a call. You won’t be disappointed.", stars:5, source:"google"},
    {name: "David L", review: "James removed an old, poured concrete foundation from a removed out building. It was too small a job for others I contacted, but James took it on willingly and at a fair price. In spite of breakdowns in rental equipment he worked diligently to finish the job, and maintained good communication throughout. I am happy with the finished job, and recommend him. I would use them again.", stars:5, source:"google"},
    {name: "Jina B", review: "James did a phenomenal job on our Crawlspace Encapsulation !! We were in a time crunch in getting our Crawlspace up to codes for inspection and the pending sale of our house! James and his wife was heaven sent!! Yes!! Team work makes the dream work! James was knowledgeable and gave some education as well on the issues and how he was going to remedy them! Not to mention red flags to look for in our new home going forward! If that isn’t a full service experience, I don’t know what is! We also had some issues with improper joist support and duct work maintenance , which was also taken care of by James with the help of his wife!! What a dynamic team!! Our Crawlspace looks amazing!!! But above that the job was done with precision, and great quality! Did I mention that Middle Tennessee Crawlspace’s prices were very reasonable? You get good QUALITY work for a great price!! Give this company a chance to earn your business.. you will not regret it!!", stars:5, source:"google"},
    {name: "Jathleen H", review:"James and his crew did a great job encapsulating the crawl space of my home. They treated the crawl space for fungus and installed a dehumidifier. Great work, great price, very happy customer!", stars:5, source:"google"},
    {name: "Paige J", review: "James came in with a price lower by a couple thousand dollars from a competitor to do a full encapsulation in our crawlspace. He did the work he promised and worked with us on getting the job in time for us to close on the sale of our home.", stars:5, source:"google"},
    {name: "Bin L", review: "Middle Tennessee Crawlspace did a Crawlspace encapsulation with a sump pump and 25 ft drain system . They were 1/2 the price of the 3 estimates I received. The work was excellent . My floor system looked new . The air inside overnight changed for the better . We were very pleased , I strongly recommend this company to all that need this service", stars:5, source:"google"},
    {name: "Kennon K", review:"We bought a new home in Hendersonville with fungus and moisture issues in the crawlspace. James beat most other bids by a couple thousand dollars. His team did a full encapsulation and de-humidification system. Looks great down there now. I highly recommend his team.", stars:5, source:"google"},
    {name: "Billy P", review: "James oversaw and they encapsulated my Crawlspace with dehumidifier and built new Crawlspace door for a much lower price than all other quotes and did an excellent job. I would highly recommend them to anyone.", stars:5, source:"google"},
    {name: "Jonas H", review: "They were very responsive and took time to explain everything. They did an excellent job and completed the work in one day. The price for Middle Tn Crawl Space was also the best price.", stars:5, source:"google"},
    {name: "Michele S", review: "I got my crawlspace vents replaced and vapor sealed. They did a great job! Very friendly and got the job done in a timely manner.", stars:5, source:"google"},
    {name: "Renee H", review: "James was very professional, informative, and affordable pricing.", stars:5, source:"google"},
    {name: "Shavonda G", review: "James is awesome. Did a great job, prompt, explained everything prior to and during the process, cleaned up afterwards, reasonable prices. You can’t go wrong choosing him. I plan to work with him in the future for other projects", stars:5, source:"google"},
    {name: "Noah L", review: "Very happy with the job they did. The encapsulation looks very good and clean. 10/10 would recommend to a friend or family member. ", stars:5, source:"ha"},
    {name: "Shovanda G", review: "Unbeatable prices, extremely prompt, great communication skills, awesome at explaining the process and what to expect, overall an excellent job! I plan to use him in the future for other projects!!!", stars:5, source:"ha"},
    {name: "Mark H.", review: "Showed up on time , did a great job ,went the extra mile to make me happy", stars:5, source:"ha"},
    {name: "Lisa L", review: "James was here within 20 minutes of my emergency call. Fixed my sump pump in a jiffy. I can sleep tonight. So thankful.", stars:5, source:"ha"},
    {name: "Emily M", review: "Couldn't recommend them enough! James was kind and informative, and kept us in the loop the whole time. His worker Brian was unbelievable and worked incredibly hard - incredibly efficient. Every time my husband and I talked to him we would say ?wow this guy is so nice? or ?wow he is working so hard?. The last day he spent 10 hours under our house working to get it finished for us. We received quotes on other company?s and their price was also the best by a long shot.", stars:5, source:"ha"},
    {name: "Robert F", review: "Had basement walls sealed to fix / prevent water leaks. The job wads done on time and on budget.", stars:5, source:"ha"},
    {name: "Elizabeth H", review: "Excellent job. Professional work with excellent communication.", stars:5, source:"ha"},
    {name: "Periann A", review: "Professional and responsive. Waterproofed basement and stopped water incursion.", stars:5, source:"ha"},
    {name: "John B", review: "Job done right and in a timely manner.", stars:5, source:"ha"},
    {name: "James W", review: "Good job , no issues quality of work was good", stars:5, source:"ha"},
    {name: "Linus L", review: "James has now finished 3 Jobs for me .l have 3 rooms in my basement bathroom kitchen bedroom large living area washer and dryer etc. The last heavy rain we were almost flooded with water from the outside front wall James and his crew dug up a 40 foot long strip 5 foot deep and 3 plus feet wide and completely sealed my home and put additional 3 drains under my sidewalk for additional protection.Now when the heavy rains come and they will I Will sleep better knowing my investments are protected.one last piece of advice I knew what I wanted but his knowledge and advice was truly helpful in making the decision who to go with.thanks!!", stars:5, source:"ha"},
    {name: "Dania L", review: "Very prompt and professional. Crawl space looks amazing and it took less than a week!", stars:5, source:"ha"},
    {name: "Linus L", review: "This is the second job they have done I am now waiting on another estimate on 2 other projects from James McCasland everything has been going well will try to use them again!", stars:5, source:"ha"},
    {name: "Linus L", review: "They were on time fast cleaned up afterwards will definitely use again very positive experience thanks!", stars: 5, source:"ha"},
    {name: "Harriet T", review: "Middle Tennessee Crawlspace did a GREAT Job encapsulating my crawl space. James was courteous and respectful throughout the entire process. They called each day to confirm the time of arrival. His entire staff were very friendly, helpful and professional", stars:5, source:"ha"},
    {name: "Jordan B", review: "Always responsive and timely. Sends photos of work so you know what has been done", stars:5, source:"ha"},
    {name: "Debbie B", review: "James is very knowledgeable about his work. He waterproofed, installed a dehumidifier, new subfloors, and new floor joists. All at a very reasonable price. James takes pride in his work and goes beyond expectations to ensure he's thorough with completion. I would highly recommend him!", stars:5, source:"ha"},
    {name: "Beverly N", review: "Our late 1950's home was in dire need of fixing our crawl space. When we looked in the space, we saw standing water, mold-damaged rafters, and a terrible odor that was dangerously unhealthy James McCashland of Middle Tennessee Crawlspace answered our call for help immediately. He thoroughly inspected the problem and, without giving a sales pitch, he explained what was needed and alternative options. Mr. McCashland gave us a Tennessee Crawlspace quote that would get rid of the water, repair rafters, remediate mold and totaly encapsulate the space. Not only was his quote very affordable, but it guaranteed the job would be the completed within the following week. He was wrong about that. All work was done, debris removed, and obnoxious order elimated in 3 days. I would certainly recommend James McCashland's Middle Tennessee Crawlspace to any person looking for affordable, prompt and honest company!", stars:5, source:"ha"},
    {name: "J S", review: "Hired mid 10 crawl to perform complete encapsulation of 2500 ft 45-year-old crawl space. They removed all old debris and old plastic vapor barrier, installed clean white threaded vapor barrier up the walls and across the floors, sealed all openings, taped up all joints and piers, installed LED lighting, added a new power line and dehumidifier treated the joists for mold and treated the ground to reduce mold and organism growth. Midtencrawls price was far below the big name companies. They provided excellent reliable and efficient personal service which *you will not get from a big name national company with fancy color brochures*. I know this for a fact because I had bids from those three other big companies and I turned them all down. Owner James McCasland is very knowledgeable and inspired a lot of confidence. He pointed out things which the three other companies did not either know about or did not bother to mention. Highly recommend this company.", stars:5, source:"ha"},
    {name: "Sam F", review: "We had reviewed 3 other companies before selecting Middle Tennessee Crawlspace. The top reason was pricing and my neighbor was having his crawlspace encapsulated and felt his information, price, and knowledge was valid. James had also worked for other companies that do encapsulation and knows the truthfulness of their promises. James was very knowledgeable about his craft, soils and what the overall key performance indicator hed be expecting. Basically, humidity and moisture goals(there is a difference I learned). James and his team provided excellent service and went above and beyond the general work that was required.", stars:5, source:"ha"},
    {name: "Tony K", review: "Great services!! Would recommend", stars:5, source:"ha"},
    {name: "Joseph C", review: "James and team did an excellent job at a competitive price. Their customer service and quality of work was exceptional. James kept me informed every step of the way- communication was top notch, and I am very happy with the results!", stars:5, source:"ha"},
    {name: "Daniel A", review: "Great job!", stars:5, source:"ha"},
    {name: "David K", review: "I have used James several times since the initial project for yearly service inspections. I enjoyed the experience with James because he was ready to explain and make suggestions that would make the project better and went to great detail in explaining the process. I would recommend him for this type of project.", stars:5, source:"ha"},
    {name: "Jen S", review: "James and his crew were absolutely wonderful â Â they were affordable, on time, and a pleasure to have on site. James was very helpful in explaining exactly what needed to be done and why, and the work they did was stellar! Couldn't recommend them enough!", stars:5, source:"ha"},
    {name: "Emily T", review: "James and his crew are absolutely wonderful. The work that they provided was above and beyond! Affordable, reliable, GREAT communication, very nice and informative! We couldnâ t have asked for better work. He was able to come out and start work the very next day after contacting him! We would 110% recommend Middle Tennessee Crawlspace!", stars:5, source:"ha"},
    {name: "Cecilla V", review: "Honest, Affordable, Exceptional: Middle Tennessee Crawlspace. Middle Tennessee Crawlspace saved us thousands of dollars! James' bid was straightforward and honest, recommending only the essentials. If you're looking for an honest bid, steer clear of those big companies that try to recoup their advertising expenses. One such company told me I needed a dehumidifier and three sump pumps, but James provided us with exactly what we needed at nearly half the cost. He installed a high-quality 100-pint dehumidifier with a built-in pump that drains directly into our plumbing line. James exemplifies exceptional customer service and operates with the highest standards of integrity. He considers a job complete only when his customers are completely satisfied. He and his crew finished our crawlspace encapsulation on time and within the agreed budget, and the quality of their work is truly stunning. The team worked quickly, was friendly, and left the job site clean. I wholeheartedly recommend Middle Tennessee Crawlspace, and I wouldn't hesitate to hire them again. Bring your business to them with confidence!"},
    {name: "Will Y", review: "It is been a long time since I have been as pleased with a service provider as I have been with Jamesâ s team at Middle Tennessee Crawlspace. They were all knowledgeable, friendly, professional and literally half the price of the other companies. I wouldnâ t hesitate to use them again and and only wish that I had had called them sooner.", stars:5, source:"ha"},
    {name: "B H", review: "The owner/operator, James McCasland was knowledgeable and prompt.", stars:5, source:"ha"},
    {name: "Ivy L", review: "This is the second time I hired Middle Tennessee Crawlspace . We had issues with cracks in our foundation . James used a commercial product to repair and waterproof the areas . He was very affordable and very detailed in his work . I highly recommend him him to any one needing work . James is an ex code inspector and is very knowledgeable in most fields in home construction and rehabilitation .Five Stars most definitely.", stars:5, source:"ha"},
    {name: "Ivy L", review: "James was excellent . He inspected our crawl space . And suggested ways to correct our moisture problems . They installed a sump pump with a drainage system and encapsulated our crawl space with a dehumidifier . They were more affordable than the completion and completed the job very quickly . I strongly recommend Middle Tennessee Crawlspace to all who need crawl space work", stars:5, source:"ha"},
    {name: "Billy Paul J", review: "James was awesome. He oversaw everything and they encapsulated my Crawlspace with a dehumidifier, built a new Crawlspace door and removed the wood decaying fungi from my floor system by hand. They beat every other quote I got and I would highly recommend them to anyone!", stars:5, source:"ha"},
    {name: "Robert F", review: "I called and the company came out the same day to do the job. The company was very polite and did what I asked along with inspection.", stars:5, source:"ha"},
    {name: "Kelly V", review: "We had another company bid on encapsulating a crawl space and they were thorough and proceeded to explain to us why it would cost so much. My husband and I decided to get another bid and during a google search we came across James and Middle Tennessee Crawlspace. He came to our home, looked at the crawlspace and upon completion of the inspection walked us through what he saw and believes we needed. Not only did he find three major issues that the others never mentioned but his quote was HALF of what this major company quoted. James and his guys were able to start right away. He was professional, proficient, and he kept us updated on the process and what we should see in the space and feel in the air in the house once they were finished. He even recommended an electrician to place a new plug for the dehumidifier in the crawlspace. He was a gem as well and we've hired him to do more electrical work. We wholeheartedly would recommend James to inspect / encapsulate your crawl space!", stars:5, source:"ha"},
    {name: "Brian H", review: "James did a first rate job encapsulating the crawl space of my home. He installed a dehumidifier and treated all the brick and beams. I would highly recommend his services!", stars:5, source:"ha"},
    {name: "Rich C", review: "Middle Tennessee Crawlspace is a must call if you want quality work, friendly workers, and a great price. James and his crew showed up and did exactly what he quoted me for. He even kept me updated throughout the 2 day project with pictures, since I was not home. It turned out great! Now we have a fully encapsulated Crawlspace, and it looks great. Highly recommend Middle Tennessee Crawlspace.", stars:5, source:"ha"},
    {name: "Daniel A", review: "They were timely, courteous, friendly, helpful, and explained everything they were doing. They encapsulated the crawlspace, wiped down and treated floor joists to prevent mold, patched a crack in a wall, and installed a dehumidifier. They were a third of the price quoted to us by a major competitor. We couldn't have been happier. We would recommend Middle Tennessee Crawlspace to anyone with crawlspace issues.", stars:5, source:"ha"},
    {name: "Rita P", review: "Excellent customer service and excellent price.", stars:5, source:"ha"},
    {name: "David K", review: "James is very knowledgeable and does a good job. I had him install a dehumidifier system, Crawlspace encapsulation, and a perimeter drainage and pump system. This was two years ago. I contacted him for our annual service and two check out a small problem. James fixed the problem and showed up in a timely manner. Good service and good products. I have had several comments on how he does his job.", stars:5, source:"ha"},
    {name: "Heidi S", review: "James is great! Kept us posted throughout the entire project and made sure that everything met our requirements and standards.", stars:5, source:"ha"},
    {name: "Kennon K", review: "We bought a new home in Hendersonville with fungus and moisture issues in the crawlspace. James beat most other bids by a couple thousand dollars. His team did a full encapsulation and de-humidification system. Looks great down there now. I highly recommend his team.", stars:5, source:"ha"},
    {name: "Jim T", review: "Friendly professional and local.", stars:5, source:"ha"},
    {name: "Linda L", review: "Excellent job on my crawlspace. I've been told by people who have been down there that it is one of the nicest crawlspace encapsulation jobs they've ever seen. Price was below other contractor quotes I'd received."},
    {name: "Thomas W", review: "They did the job as expected", stars:5, source:"ha"},
    {name: "Clifford L", review: "I needed my home level also needed new ductwork put in to the ac/ heating unit they said would do also after they got done with the crawlspace also added 6 inches of insulation in the attic redid the ductwork box reset my unit also they went into crawlspace and set new jacks to level the house up because some of doors was not open good but when everything was done the house was a lot warmer the was floors was level good and ductwork all worked great thanks for doing and awesome job middle Tennessee crawlspace.", stars:5, source:"ha"},
    {name: "David K", review: "The job was well done. He didnâ t try to up sale you. If you had questions he would explain your options and give you the prices and not pressure you. Good looking job and quality work and equipment, Would recommend and hire again if needed.", stars:5, source:"ha"},
    {name: "David F", review: "The work they did was solid and worth the money.", stars:5, source:"ha"},
    {name: "Erica C", review: "They encapsulated my crawlspace and took care of other jobs I needed done so I didn&amp;amp;#39;t have to hire several other companies. My crawlspace looks great and it was done for a reasonable price.", stars:5, source:"ha"},
    {name: "James Donald N", review: "Very nice people.", stars:5, source:"ha"},
    {name: "Robert R", review: "Work was done per schedule and on time and for cost. Crew was great and all professional.", stars:5, source:"ha"},
    {name: "Carlton D", review: "They were affordable . They finished by the time they mentioned. The odor went away instantly. My crawlspace smells great now. I am able to store my stuff without worrying about it getting ruined. My wife and I are very happy. Great customer service. I would definitely recommend. Looking forward to the health benefits due to better air quality. They went above and beyond what was expected.", stars:5, source:"ha"},
    {name: "Geoffrey W", review: "Very knowledgeable on many home projects. If they can't do it, they know someone that can.", stars:5, source:"ha"},
    {name: "Bruce V", review: "Punctual, affordable, highly recommended. Many services offered. Great service.", stars:5, source:"ha"},
    {name: "Peggy C", review: "Very nice people", stars:5, source:"ha"},
    {name: "Micah M", review: "Middle Tennessee Crawlspace was a lifesaver during our home buying process. We noticed a mildew smell inside of the house, and they came out during our inspection and surveyed both the attic and crawlspace. They provided WAY more information than the home inspector, as well as reasonable quotes to remedy the moisture and insulation problems if purchased. I highly recommend Middle Tennessee Crawlspace to anyone!", stars:5, source:"ha"},
    {name: "Margaret M", review: "They were so nice to work with. They did a great job and were here when they said they would be. My crawlspace was mold mildew and now it is encapsulated and looks great and a dehumidifier is working great.", stars:5, source:"ha"},
    {name: "Linda L", review: "I have had several people in my crawlspace and they have said that the work of Middle Tennessee Crawlspace is some of the nicest jobs they have seen.", stars:5, source:"ha"},
    {name: "Amy F.", review: "What a wonderful experience. The owner and his lovely wife came and removed an oversized refrigerator and a stove for me. They were so polite and kind. They were very professional and easy to talk to. I will definitely call them again for my next project. The company does much more than just crawlspaces, so if you need any handyman stuff done you should absolutely give them a call.", stars:5, source:"ha"},
]

// randomize the array on each page load
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Carousel item template:
/* <div class="carousel-item active">
    <p><i class="bi bi-star-fill"></i>...</p>
    <p>Loved James and his crew! I would give 6 stars if I could!</p>
    <p>-John J.J.H.S. via Google</p>
</div> */

function setup_review_list(list) {
    // super professional debugging
    // console.log("Setting up review list");
    // console.log("list is length " + list.length)
    list = shuffleArray(list); // Shuffle the list each time to have more reviews showing up
    for (let i = 0; i <= Math.max(list.length, 25); i++) { // Select all reviews to a maximum of 25. Maximum set to avoid slower page load times.
        if (i == 0){
            review_element = '<div class="carousel-item active"><p>'; // set first element to active
        } else {
            review_element = '<div class="carousel-item"><p>'; // proceeding elements are not active
        }

        for (let stars = 0; stars <= list[i]["stars"]-1; stars++) {
            review_element += '<i class="bi bi-star-fill"></i>'; // Dynamically add stars
        }

        review_element += '</p><p class="review_text">' + list[i]["review"] + '</p><p>- ' + list[i]["name"] + ' via '
        // add the review source
        if (list[i]["source"] == "google") {
            review_element += "Google Reviews";
        } else if (list[i]["source"] == "ha" || list[i]["source"] == "homeadvisor") {
            review_element += "Home Advisor";
        } else {
            review_element += "Online Review"; // Fallback in case of mispellings or mistakes
        }

        review_element += "</p></div>";
        
        $("#review-carousel").append(review_element);
        console.log("appended review from " + list[i]["name"]);
    }
}

$(document).ready(function () {
    console.log("webpage loaded");
    // dynamic loading of the review list
    setup_review_list(review_list);
})